[package]
name = "strimilar"
version = "0.1.0"
edition = "2018"
authors = ["Grzegorz SÅ‚owik"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]